### ISSUE TITLE
Could not find br.com.uol.pagseguro.plugpagservice.wrapper:wrapper:1.7.6.

### ISSUE THREAD

**Issue by FaelN1** [lexitbr/react-native-plugpag-lib#1]
Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * What went wrong: Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'. > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'. > Could not find br.com.uol.pagseguro.plugpagservice.wrapper:wrapper:1.7.6. Required by: project :app * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 15s.

**Comment by mCodex** [comment]
@FaelN1 you can use the latest version:

`implementation 'br.com.uol.pagseguro.plugpagservice.wrapper:wrapper:1.28.2'`
